# Set keymap. Choose one.
setxkbmap se-lenovo-s430 -option 'ctrl:nocaps'  # Copy to /usr/share/X11/xkb/symbols/
# xkbcomp ~/.local/share/infect/misc/x11/keymaps/macbook.xkb :0

# Set background
feh --bg-scale ~/.local/share/infect/misc/x11/wallpapers/current

# Setup some x prefs
xset r rate 330 45 &
xset -b
xrfb ~/.Xresources
xbindkeys &
xinput set-button-map 11 1 2 3 5 4 6 7 8 9 10 11 12
redshift -l 57:18 -t 5500k 4500k

exec xsetroot -cursor_name left_ptr &
exec unclutter -idle 1 -root &
exec keynav &

# Autostart some apps
exec ~/.dropbox-dist/dropboxd &
exec /usr/bin/volumeicon &
exec /usr/bin/twmnd &

exec herbstluftwm --locked -c ~/.local/share/infect/misc/x11/hlwm/autostart &> ~/.local/logs/hlwm.log
