#!/usr/bin/env bash

check_updates() {
    checkupdates 2&> /dev/null
    yay -Qu 2&> /dev/null

}

is_running() {
    if [ `pgrep -x yay | wc -l` == 0 ] && [ `pgrep -x pacman | wc -l` == 0 ] ; then
        echo "false"
    else
        echo "true"
    fi
}

if [ $(is_running) == "false" ] ; then
    # Run check_updates and don't stick around for it to finish.
    # On to the animations, yeah!
    check_updates &

    # Animate updating status
    while [ $(is_running) == "true" ] ; do
        echo "%{T5}%{T-}"
        sleep 1
    done

    available_updates=$(yay -Qu | wc -l)
    if [ $available_updates == 0 ]; then
        echo ""
    else
        color=$(xrdb -q | grep "*color1:" | cut -f2)
        echo "%{F$color} $available_updates%{F-}"
    fi

fi
