#!/usr/bin/env bash

URGENT=`xrdb -query | grep "*.urgent" | cut -f2`
FOREGROUND=`xrdb -query | grep "*.color15" | cut -f2`

check_updates() {
    checkupdates 2&> /dev/null
    yay -Qu 2&> /dev/null

}

is_running() {
    if [ `pgrep -x yay | wc -l` == 0 ] && [ `pgrep -x pacman | wc -l` == 0 ] ; then
        echo "false"
    else
        echo "true"
    fi
}

if [ $(is_running) == "false" ] ; then
    # Run check_updates and don't stick around for it to finish.
    # On to the animations, yeah!
    check_updates &

    # Animate updating status
    while [ $(is_running) == "true" ] ; do
        echo "%{F$FOREGROUND}%{T4}%{T-}%{F-}"
        sleep 1
    done

    available_updates=$(yay -Qu | wc -l)
    if [ $available_updates == 0 ]; then
        echo "%{F$FOREGROUND}%{F-}"
    else
        # color=$(xrdb -q | grep "*color1:" | cut -f2)
        # color="#A54242"
        echo "%{F$URGENT} $available_updates%{F-}"
    fi

fi
