#!/bin/bash

function hc() {
    herbstclient "$@"
}

hc emit_hook reload

## Remove all existing keybindings
hc keyunbind --all

## Keybinding variables
Mod=Mod1
AltMod=Mod4

## Basics
hc keybind $Mod-$AltMod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-q close

##  Applications
hc keybind $Mod-space spawn dmenu_exec
hc keybind $Mod-Shift-space spawn dmenu_www

# Tags
TAG_NAMES=( {1..5} )
TAG_KEYS=( {1..5} 0 )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

## Cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible
hc keybind $Mod-Right use_index +1 --skip-visible
hc keybind $Mod-Left  use_index -1 --skip-visible

## Layouting
hc keybind $Mod-r remove
hc keybind $Mod-$AltMod-space cycle_layout 1
hc keybind $Mod-$AltMod-Shift-space cycle_layout -1
hc keybind $Mod-u split vertical 0.5
hc keybind $Mod-o split horizontal 0.5
hc keybind $Mod-Shift-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

## Rresizing
RESIZESTEP=0.05
hc keybind $Mod-Control-h resize left +$RESIZESTEP
hc keybind $Mod-Control-j resize down +$RESIZESTEP
hc keybind $Mod-Control-k resize up +$RESIZESTEP
hc keybind $Mod-Control-l resize right +$RESIZESTEP

## Mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

## Focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-t jumpto urgent
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

## Lockscreen
hc keybind $Mod-Shift-BackSpace spawn xlock

## Run-or-raisers
# Terminals
hc keybind $Mod-Return spawn mor main
hc keybind $Mod-Shift-Return spawn urxvt
hc keybind $Mod+a spawn mor alt
hc keybind $Mod+d spawn mor dev

# Browsers
hc keybind $Mod-b spawn ror "luakit" '("luakit" "luakit")' "luakit"
hc keybind $Mod-Shift-b spawn luakit

# Browsers
hc keybind $Mod-Shift-d spawn pcmanfm

# Spotify
hc keybind $Mod-s spawn ror "Spotify": '("spotify" "Spotify")' "spotify"
# hc keybind $Mod-s spawn ror "spotify" '("spotify" "Spotify")' "spotify"

## Colors
# hc set frame_border_active_color '#222222'
hc set frame_border_active_color '#9fbc00'
hc set frame_border_normal_color '#101010'
hc set frame_bg_transparent 1
hc set frame_border_width 1
hc set window_border_width 3
hc set window_border_inner_width 1
hc set window_border_normal_color '#454545'
hc set window_border_active_color '#9fbc00'
hc set always_show_frame 0
hc set frame_gap 5
hc set window_gap 5
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0


## Rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off

## Unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# herbstclient chain $cmds&

# Start the damn bar, yeah.
pkill storm &> /dev/null
source ~/.local/share/infect/misc/x11/storm/bin/activate
~/.local/share/infect/misc/x11/storm/bin/storm &
