#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

###
## Variables
#

# userresources=$HOME/.Xresources
# usermodmap=$HOME/.Xmodmap
# sysresources=/etc/X11/xinit/.Xresources
# sysmodmap=/etc/X11/xinit/.Xmodmap

# DEFAULT_SESSION='i3 --shmlog-size 0'

###
## Merge defaults and keymaps
#

# if [ -f $sysresources ]; then
#     xrdb -merge $sysresources
# fi

# if [ -f $sysmodmap ]; then
#     xmodmap $sysmodmap
# fi

# if [ -f "$userresources" ]; then
#     xrdb -merge "$userresources"
# fi

# if [ -f "$usermodmap" ]; then
#     xmodmap "$usermodmap"
# fi

# # start some nice programs

# if [ -d /etc/X11/xinit/xinitrc.d ] ; then
#     for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
#         [ -x "$f" ] && . "$f"
#     done
#     unset f
# fi

# ------------------

###
## Set keymap. Choose one.
#

# Lenovo s430
setxkbmap se-lenovo-s430 -option 'ctrl:nocaps'  # Ensure file in /usr/share/X11/xkb/symbols/

# Macs (native)
# xkbcomp ~/.dotfiles-local/conf-comps/macbook/files/macbook.xkb :0

# Virtualbox Stuff
# VBoxClient-all
# setxkbmap se-mac-vbox # Ensure file in /usr/share/X11/xkb/symbols/S

# ------------------

###
## Setup some x prefs
#

xset r rate 200 40 &
xset -b

# xrfb ~/.Xresources
# xbindkeys &
# xinput set-button-map 11 1 2 3 5 4 6 7 8 9 10 11 12

# exec xsetroot -cursor_name left_ptr &
# exec unclutter -idle 1 -root &
# exec keynav &

# Autostart some apps
# redshift -l 57:18 -t 5500k 4500k

# exec /usr/bin/start-pulseaudio-x11 &
# exec /usr/bin/twmnd &

# Set background
# feh --bg-scale ~/.wallpapers/current

# ------------------

# Actually launch the WM. Choose one.

# export XORG_WM="hlwm"
# exec herbstluftwm --locked -c ~/.local/share/infect/misc/x11/hlwm/autostart &> ~/.local/logs/hlwm.log

export XORG_WM="i3"
exec i3 -V &> $HOME/.local/logs/i3.log

# get_session(){
#     local dbus_args=(--sh-syntax --exit-with-session)
#     case $1 in
#         awesome) dbus_args+=(awesome) ;;
#         bspwm) dbus_args+=(bspwm-session) ;;
#         budgie) dbus_args+=(budgie-desktop) ;;
#         cinnamon) dbus_args+=(cinnamon-session) ;;
#         deepin) dbus_args+=(startdde) ;;
#         enlightenment) dbus_args+=(enlightenment_start) ;;
#         fluxbox) dbus_args+=(startfluxbox) ;;
#         gnome) dbus_args+=(gnome-session) ;;
#         i3|i3wm) dbus_args+=(i3 --shmlog-size 0) ;;
#         jwm) dbus_args+=(jwm) ;;
#         kde) dbus_args+=(startkde) ;;
#         lxde) dbus_args+=(startlxde) ;;
#         lxqt) dbus_args+=(lxqt-session) ;;
#         mate) dbus_args+=(mate-session) ;;
#         xfce) dbus_args+=(xfce4-session) ;;
#         openbox) dbus_args+=(openbox-session) ;;
#         *) dbus_args+=($DEFAULT_SESSION) ;;
#     esac

#     echo "dbus-launch ${dbus_args[*]}"
# }

# exec $(get_session)
