#!/bin/sh -e

PROGDIR=$(dirname "$(readlink -f "$0")")

FILE="emoji_ranked.txt"
if [ "$1" == "long" ] ; then
    FILE="emoji.txt"
fi

# Fix a bug where active window is lost if dmenu pops under cursor
active_window=$(xdotool getactivewindow)

# Replace the variant selector code point that dmenu can't display
# emoji=$(cat "$PROGDIR/emoji_ranked.txt" | grep -v "^#" | sed $'s/\ufe0f//' | dmenu -h 40 -i -l 20 | sed 's/ .*//')
emoji=$(cat "$PROGDIR/$FILE" | grep -v "^#" | sed $'s/\ufe0f//' | dmenu -h 40 -i -l 10 | sed 's/[0-9]*    //' | sed 's/ .*//' | sed 's/\\r//')

# echo $emoji

# exit 0
xdotool windowactivate "$active_window"

if [ -z "$emoji" ]; then
    exit
fi

# Bring the variant selector code point back
emoji=$(grep "$emoji" "$PROGDIR/$FILE" | grep -v "^#"  | sed $'s/\ufe0f//' | sed 's/[0-9]*    //' | sed 's/ .*//')

if [ "$1" = copy ]; then
    printf "$emoji" | xclip -selection clipboard
    echo "Copied $emoji to clipboard!"
else
    xdotool type -delay 100 "$emoji"
fi
