#!/usr/bin/env sh

name="$1"
run_cmd="$2"

# session="$name@`hostnamectl hostname`"
count=`xdotool search --name "$name" | wc -l`
if [ "$count" -ne 0 ] ; then
    ## Raise if window is open already.
    i3-msg "[title=(?i)$name] focus" > /dev/null
else
    ## No window found to be raised, run it instead. 
    
    # Determine appropriate terminal emulator.
    if command -v alacritty > /dev/null ; then
        terminal_cmd="alacritty -t $name -e"
    elif command -v st > /dev/null ; then
        terminal_cmd="st -t $name -e"
    elif command -v urxvt > /dev/null ; then
        terminal_cmd="urxvt -name $name -e"
    else
        echo "No suitable terminal detected. Exiting..."
        exit 1
    fi
    
    # Determine appropriate shell.
    if command -v zsh > /dev/null ; then
        shell_cmd="zsh -c"
    elif command -v bash > /dev/null ; then
        shell_cmd="bash -c"
    else
        echo "No suitable terminal detected. Exiting..."
        exit 1
    fi
    
    # Set up the tmux command and check if there is a command that's supposed
    # be run in the tmux session.
    tmux_cmd="source $XDG_CONFIG_HOME/zsh/zshrc ; tmux new -A -s $name"
    if [ "$run_cmd" != "" ] ; then
    	tmux_cmd+=" $run_cmd"
    fi

    # Actually run the thing and focus...
    ($terminal_cmd $shell_cmd "$tmux_cmd" &)
    sleep 0.2
    # i3-msg "[title=(?i)$session] focus"
    i3-msg "[title=(?i)$name] focus" > /dev/null
fi
